### PR TITLE
feat(launchServer-options) (proxy, browser args)

### PR DESCRIPTION
**Pull request by vgavro**
More options to configure lauchServer from environment variables, fixes issue on providing custom port

### CODE REVIEW

**Comment by vgavro** [comment]
Usage example:
```
ssh -D 0.0.0.0:10000 -qCNf MY_REMOTE_MACHINE_AS_PROXY
docker run -e BROWSER_PROXY_SERVER=socks5://host.docker.internal:10000 -e BROWSER_ARGS=--ignore-certificate-errors -e BROWSER_TIMEOUT=60000 -p 53333:53333 --add-host=host.docker.internal:host-gateway chromium-server
```

**Comment by vgavro** [comment]
It's worth to mention options in README (each option), but i don't want to mess with my other merge request for that, maybe i'll add separate PR after merge what do you think

**Review by JacobLinCool — APPROVED** [review]

**Comment by JacobLinCool** [comment]
I am not sure if just passing the cli arguments  
```
docker run -e BROWSER_TIMEOUT=60000 -p 53333:53333 chromium-server --ignore-certificate-errors
```
would be better than:  
```
docker run -e BROWSER_ARGS=--ignore-certificate-errors -e BROWSER_TIMEOUT=60000 -p 53333:53333 chromium-server
```

What do you think? Could this cause issues when running with docker-compose or other management tools?

**Comment by vgavro** [comment]
> I am not sure if just passing the cli arguments
> 
> ```
> docker run -e BROWSER_TIMEOUT=60000 -p 53333:53333 chromium-server --ignore-certificate-errors
> ```
> 
> would be better than:
> 
> ```
> docker run -e BROWSER_ARGS=--ignore-certificate-errors -e BROWSER_TIMEOUT=60000 -p 53333:53333 chromium-server
> ```
> 
> What do you think? Could this cause issues when running with docker-compose or other management tools?


well,  while approach you're proposing looks more natural, disadvantages are:

* mixing `playwright server` arguments and `browser` arguments. Also note - while `playwright` is using some browser arguments by default (which can be in conflict with provided `options.args`), so this is not "exactly" args with which browser is started. so more natural approach adds ambiguity.

* breaking consistency where all `launchServer(options)` object is populated from ENV with same naming - so 1. by variable names you can predict where they are actually binded in `options` object strucutre 2. standard way to configure container is using ENV,  so using actual arguments in `docker-compose` or kubernetes `configMap` will be more tricky.

**Comment by vgavro** [comment]
so in short my point of view - we can add server.js ARGUMENTS to configure, which will **mirror** env configuration, but not mix it.

**Comment by vgavro** [comment]
I'll check tests failing and update PR!
Thanks for quick response and great work with this!

**Pull request merged**
